#pragma once
#ifndef MY_VOCA_LIST_H 
#define MY_VOCA_LIST_H
#include "MyVoca.h"

int NUM_MY_TOEIC_VOCA = 100; ////////////////////
MyVoca myToeicVocaList[]; // defined in MyVocaList.cpp 

MyVoca myToeicVocaList[] =
{

	MyVoca("mean", NOUN, { "average", "norm", "median", "middle", "midpoint", "(ant) extremity" }, { "the mean error", "the golden mean", "the arithmetical mean", "the geometric mean" }),
	MyVoca("mean", ADJ, { "nasty", "poor", "middle", "miserly", "paltry" }, { "a man of mean intelligence", "a mean appearance" }),
	MyVoca("mean", VERB, { "require", "denote", "intend" }, { "What do you mean by \"perfect\" \?" }),
	MyVoca("offer", NOUN, { "proposal" }, { "He accepted out offer to write the business plan." }),
	MyVoca("offer", VERB, { "to propose" }, { "She must offer her banker new statistics in order to satisfy the bank's requirement for the loan." }),
	MyVoca("compromise", NOUN, { "give-and-take", "bargaining", "accommodation" }, { "The couple made a compromise and ordered food to take out." }),
	MyVoca("compromise", VERB, { "settle", "conciliate", "find a middle ground" }, { "He does not like sweet dishes so I compromised by adding just a small amount of sugar." }),
	MyVoca("delegate", NOUN, { "representative", "agent", "substitute" }, { "" }),
	MyVoca("delegate", VERB, { "authorize", "appoint", "designate" }, { "" }),
	MyVoca("foster", VERB, { "nurture", "raise", "promote", "advance" }, { "" }),
	MyVoca("foster", ADJ, { "substitute", "adoptive", "stand-in" }, { "" }),
	MyVoca("imperative", ADJ, { "authoritative", "vital" }, { "" }),
	MyVoca("imperative", NOUN, { "necessity", "essential", "requirement" }, { "" }),

	MyVoca("recruit", NOUN, {"newcomer", "trainee", "rookie"}, {"The two soldier's deaths followed those of two other recruits at the barracks who also died from gunshot wounds."}),
	MyVoca("recruit", VERB, { "employ", "engage", "hire" }, { " The organizers of the festival will recruit 10 million people across the globe, who will participate by each donating £Ü1,000. " }),
	MyVoca("sophisticate", NOUN, { "Trendy", "jetsetter", "trendsetter" }, { "Today's award winners are intelligent and sophisticate." }),
	MyVoca("sophisticate", VERB, { "educate", "school", "tutor" }, { "For any of these initiatives to be successful, they should seek to inform, inspire and sophisticate but never patronize the audience." }),
	MyVoca("refrain", NOUN, { "exhortation", "buzzword", "chorus", "catchphrase" }, { "Numerous refrains were made, mostly against councillors by other councillors; there was a tit-for-tat element. " }),
	MyVoca("refrain", VERB, { "desist", "abstain", "cease", "renounce" }, { "Our managing director is asking everyone in the overseas offices to refrain from discussing the merger with anyone outside the company. " }),
	MyVoca("elaborate", ADJ, { "intricate", "sumptuous", "rich"," elegant", "ostentatious"}, {"Artistic swimming is better known as synchronized swimming or water ballet as FINA officially changed its name in 2017. It combines swimming, dance and gymnastics as participants perform elaborate moves in the water with music."}),
	MyVoca("elaborate", VERB, { "complicated", "intricate", "detailed", "involved", "sophisticated"}, {"Could you elaborate on that a little; why is risk management peculiarly critical for Customs and Excise? "}),
	MyVoca("resolve", NOUN, { "resolution","determination", "steadfastness", "tanacity", "doggedness", "firmness"}, {"Such pessimism when studying the situation should not diminish our resolve when we decide to go in."}),
	MyVoca("resolve", VERB, { "decide" "determine", "undertake", "agree"}, { "He accepted out offer to write the business plan." }),
	MyVoca("substitute", ADJ, { "supernumerary", "extra", "auxiliary", "additional", "ancillary", "temporary", "standby"}, {"Tenders for additional single role minehunters are being assessed ; two substitute oiler replenishment vessels are under construction."}),
	MyVoca("substitute", NOUN, { "alternate", "alternative", "replacement", "stand-in", "locum", "surrogate", "proxy", "deputy", "reserve"}, {"Despite the ban, the Ministry of Environment expects there will not be a huge inconvenience to consumers as substitute containers have been in wide use for years."}),
	MyVoca("substitute", VERB, { "relieve", "replace", "exchange", "switch", "swap"}, {"The rise in official participation cannot compensate or substitute for the wider civic disengagement that is taking place."}),
	MyVoca("frequent", ADJ, { "recurrent", "common", "everyday", "normal", "regular", "numerous", "many", "repeated"}, {"Geological experts have been speculating that an eruption could take place within a few years based on the signs including frequent earthquakes occurring in the vicinity of the mountain."}),
	MyVoca("frequent", VERB, { "visit", "haunt", "patronize"}, {"It should be displayed in every pub or wine bar frequented by teenagers and young adults, and in every supermarket that stockpiles cheap alcohol."}),
	MyVoca("retail", NOUN, { "trade", "selling", "marketing", "merchandising", "merchandizing", "wholesale", "sales"}, {"It is yet another example of discrimination against the retail market by issuers within the bond industry."}),
	MyVoca("retail", VERB, { "sell", "go", "trade", "vend" }, { "I want to go back to my roots, and retail software solutions instead. Selling software would be more of a challenge for me." }),
	MyVoca("invoice", NOUN, { "statement", "demand", "account" }, { "During the quarter invoice levels increased by 59pc sequentially and new business helped quarterly revenue to climb 19pc." }),
	MyVoca("invoice", VERB, { "bill", "charge", "debit" }, { "If those not in cash businesses used to invoice every month, they are now invoicing every week." }),
	MyVoca("subsidiary", ADJ, { "supplementary", "auxiliary", "ancillary", "additional", "contributory", "secondary", "extra"}, {"Their main reason for not buying the car was that it was too big -- subsidiary reasons were the style and quality. "}),
	MyVoca("subsidiary", NOUN, { "company", "firm", "holding", "business", "affiliate", "division", "branch"}, {"If you could speak to our group about the legal aspects of establishing a subsidiary in the U.S., we'd be much grateful."}),
	MyVoca("audit", NOUN, { "review", "check", "inspection", "examination" }, { "'We consider injecting the remaining amount is better, but the plan may be scrapped if protests continue,' he said at the National Assembly audit of state-run banks at the Industrial Bank of Korea headquarters in Seoul." }),
	MyVoca("audit", VERB, { "check", "review", "inspect", "examine", "assess", "appraise" }, { "In particular, the report will audit why proportionately few children from deprived backgrounds win places at university. " }),
	MyVoca("yield", NOUN, { "harvest", "crop", "produce", "vintage"}, {"It has an above average dividend yield of 4 per cent and is trading on about 11 times forecast earnings."}),
	MyVoca("yield", VERB, { "produce", "bear", "generate", "return" }, { "Whereas one hectare (2.47 acres) produces three or four tons of corn, the same area will yield 100 tons of sugar cane." }),
	MyVoca("affiliate", NOUN, { "associate", "partner", "colleague", "member" }, { "Not only has the company hired new employees, but it is also making various efforts to cooperate with its affiliates." }),
	MyVoca("affiliate", VERB, { "link", "connect", "join", "associate", "conglomerate" }, { "If a union chooses by balloting its members to affiliate, the size of the affiliation is determined by each union." }),
	MyVoca("weave", NOUN, { "pile", "texture", "nap" }, { "She praised Scarlett, the designer who made the clothes, saying it had a special weave." }),
	MyVoca("weave", VERB, { "interlace", "lace", "intertwine", "plait", "knit", "entwine", "merge" }, { "This action-roleplay game allows you to weave your own tale of heroic endeavour or dastardly deeds." }),
	MyVoca("compromise", NOUN, { "cooperation", "negotiation", "concession" }, { "Anyway, I think compromise on the price would be the best way to finish the work quickly." }),
	MyVoca("compromise", VERB, { "cooperate", "bargain", "negotiate" }, { "May I have his phone number to compromise with him on the matter I mentioned last time?" }),
	MyVoca("secure", ADJ, { "safe", "protected", "locked", "sheltered" }, { "Amusement park employees receive a lot of education and training to drive secure rides that users can ride with confidence." }),
	MyVoca("secure", VERB, { "safeguard", "fortify", "lock" }, { "As the importance of technology increases in the era of the fourth industrial revolution, competition for companies to secure software developers is intensifying recently." }),
	MyVoca("quote", NOUN, { "citation", "line", "passage", "extract", "reference", "excerpt" }, { "When writing an essay, it is very essential to write quotes cited in each chapter." }),
	MyVoca("quote", VERB, { "cite", "recite", "repeat", "mention", "parrot" }, { "Writing by quoting famous words or phrases from famous poems is a good way to attract readers' attention." }),
	MyVoca("artificial", ADJ, { "false", "fake", "mock", "reproduction", "insincere", "pretend", "contrived" }, { "Before humans are born, determining traits through artificial genetic manipulation will create many problems." }),
	MyVoca("attribute", VERB, { "ascribe", "assign", "accredit" }, { "I attribute our success of this big project to everyone's efforts, passions, teamwork and collaboration." }),
	MyVoca("attribute", NOUN, { "quality", "characteristic", "part", "trait", "feature", "point", "power"}, {"Teacher is a job that teaches children, so it is necessary to have many attributes."}),
	MyVoca("merge", VERB, { "combine", "unite", "join" }, { "By merging with that company, our company was able to easily enter the Japanese market." }),
	MyVoca("consecutive", ADJ, { "successive", "serial", "uninterrupted", "following" }, { "The club won five consecutive games, but subsequently lost in home to rivals, halting the gains." }),
	MyVoca("lattice", NOUN, { "frame", "matrix", "mesh" }, { "lattice structures are frequently used in chemistry to create arrangements and stable structures for atoms." }),
	MyVoca("organic", ADJ, { "carbon-based", "biological", "living, natural" }, { "He said that it is the most important to be healthy in body and mind while living a very regular life and eating only organic food." }),
	MyVoca("resonant", ADJ, { "booming", "ringing", "echoing" }, { "She still has a deep resonant voice and sings her best to pass the audition." }),
	MyVoca("manipulate", VERB, { "operate", "work", "deploy", "use", "handle", "control", "influence" }, { "After his success as a writer, he used his power to manipulate people at will." }),
	MyVoca("alleviate", VERB, { "ease", "lessen", "improve", "assuage", "lighten", "relieve" }, { "You can alleviate  the spicy taste by adding sugar, and you can also alleviate it through milk or cheese." }),
	MyVoca("variance", NOUN, { "alteration", "modification", "change" }, { "This month's temperature unusual variance from the previous year, and the heat will get faster every year." }),
	MyVoca("congruent", ADJ, { "corresponding", "similar", "consistent", "matching", "fitting", "harmonizing" }, { "Tessellation is one of many examples of mathematics and art integration, which means filling the space with a congruent figure." }),
	MyVoca("augmented", ADJ, { "increased", "amplified", "enlarged" }, { "Augmented reality, similar to virtual reality, is often described as bound, but there are differences." }),
	MyVoca("conjecture", NOUN, { "guesswork", "estimation", "guess", "inference", "surmise", "supposition" }, { "Such conjecture eventually ate her up and she was in the house for weeks and no one saw her outside." }),
	MyVoca("conjecture", VERB, { "estimate", "imagine", "speculate", "infer" }, { "The early morning planet crash was already a conjectured conclusion, which became a hot topic for many people." }),
	MyVoca("derivative", ADJ, { "copied", "unoriginal", "imitative" }, { "A culture derivative from one culture creates another, and various cultures continue to be created according to the times." }),
	MyVoca("derivative", NOUN, { "offshoot", "byproduct", "result", "product" }, { "Derivatives make words more systematic and rich, and there are various derivations in Korean as well as English." }),
	MyVoca("coherent", ADJ, { "intelligible", "clear", "comprehensible", "logical", "rational", "lucid" }, { "The teacher says he couldn't ask for more questions because they all made coherent claims." }),
	MyVoca("proprietary", ADJ, { "branded", "registered", "commercial", "protective", "jealous", "possessive"}, {"With the merger and acquisition this time, it became possible to operate proprietary, which led to a rise in the prices of the company's exports."}),
	MyVoca("stringent", ADJ, { "severe", "strict", "rigorous", "harsh", "stern", "tough", "inflexible", "rigid" }, { "Some say that the only way to solve this problem is through stringent regulation and severe punishment." }),
	MyVoca("stagnant", ADJ, { "still", "motionless", "quiet", "stationary", "sluggish", "torpid", "dull", "dormant" }, { "Academics talk a lot about the stagnant economy worldwide, and solving it will be the most important task." }),
	MyVoca("contingency", NOUN, { "eventuality", "possibility", "likelihood", "exigence", "emergency", "incident" }, { "For everything, including small things, planning for contingency is the most important thing especially for execution of duty." }),
	MyVoca("impending", ADJ, { "imminent", "looming", "approaching", "coming", "future", "forthcoming"}, {"Unaware of the impending disaster, he was intoxicated by his present happy life and blunted by everything."}),
	MyVoca("ecology", NOUN, { "biology", "ecosystem", "conservationism", "bionetwork", "environmentalism" }, { "I thought preserving the ecology was for all of us, and at the same time I wondered what I should do for it." }),
	MyVoca("eradicate", VERB, { "eliminate", "destroy", "exterminate" }, { "Every time a lot of events like that happen, i still feel there is eradicated discrimination in our society." }),
	MyVoca("imperative", ADJ, { "domineering", "authoritative", "bossy", "vital", "crucial", "urgent", "important" }, { "She left the classroom in a imperative and I quickly left the classroom and tried to chase her, but it wasn't enough." }),

	MyVoca("extinction", NOUN, {"death", "annihilation", "extermination", "loss", "elimination", "disappearance"}, {"There are many reasons for dinosaur extinction, but the most representative reason is the collision between Earth and meteorites."}),
	MyVoca("prescribe", VERB, { "recommend", "suggest", "advise", "propose", "counsel", "advocate" }, { "The World Health Organization (WHO) has prescribed the issue legally, but it has not changed so far, and the pros and cons are at odds." }),
	MyVoca("deficient", ADJ, { "lacking", "scarce", "underprovided" }, { "It has been divided into A and B and has been tested for weeks, and the findings will be based on the effects of deficient eating habits." }),
	MyVoca("aggravate", VERB, { "worsen", "exacerbate", "exaggerate", "heighten", "intensify", "magnify" }, { "I didn't know my involvement in the argument between Jamie and Tom only made things aggravate." }),
	MyVoca("diagnose", VERB, { "identify", "analyze", "spot", "detect" }, { "After completing all the diagnoses, he could not return home until night and left early the next morning." }),
	MyVoca("pertinent", ADJ, { "relevant", "apposite", "applicable", "germane", "valid" }, { "It took a pertinent reason to change his mind, and we gathered together to find a way." }),
	MyVoca("nutrition", NOUN, { "nourishment", "diet", "food", "sustenance" }, { "At a time when food waste is maximizing, there are still many people in the world who die of insufficient nutrition." }),
	MyVoca("abate", VERB, { "decrease", "stop", "fall", "end", "lessen", "subside", "terminate" }, { "The cold abate around this time of year, and this cycle is expected to shorten this year." }),
	MyVoca("investigate", VERB, { "examine", "explore", "inspect", "study", "consider", "probe", "scrutinize" }, { "Amid public anger, the South Korea government has asked the prosecution to investigate the case." }),
	MyVoca("broaden", VERB, { "widen", "extend", "increase" }, { "Because it is important to broaden the range of use, They said it will launch prototypes first." }),
	MyVoca("fascinate", VERB, { "captivate", "charm", "attract" }, { "According to one psychological theory, people are often fascinated to people who are different from themselves." }),
	MyVoca("description", NOUN, { "account", "report", "explanation", "portrayal", "picture", "narrative" }, { "As if I was dreaming, she vividly described what she had experienced, and this experience surprised me." }),
	MyVoca("attainment", NOUN, { "skill", "ability", "talent" }, { "This requires a curriculum overhaul, and academies  need to establish good behavior in order to raise attainment." }),
	MyVoca("substantial", ADJ, { "considerable", "sizeable", "plentiful", "ample", "big", "generous" }, { "The incident has left him in a situation where he has to pay a substantial penalty, and legal action is under way to avoid it." }),
	MyVoca("punctual", ADJ, { "prompt", "on time", "in good time", "on the dot" }, { "I think punctuality is the most basic problem in relationships and everything, so if not, I think it's important to try to be punctual." }),
	MyVoca("comprehend", VERB, { "understand", "know", "realize", "grasp", "get", "follow", "twig" }, { "She didn't seem to comprehend anything she learned today, so I approached her and helped her understanding." }),
	MyVoca("expanse", NOUN, { "area", "span", "spread", "stretch", "vastness", "breadth", "region" }, { "A wide expanse of sea  gives me a sense of security, so I regularly travel to nature." }),
	MyVoca("prohibit", VERB, { "forbid", "ban", "bar", "veto", "proscribe", "exclude", "outlaw", "disallow" }, { "Smoking indoors has been prohibited since last year, but there are still people who violate the law." }),
	MyVoca("regulate", VERB, { "control", "order", "adjust" }, { "The government has come up with various regulatory policies to regulate soaring gold prices but has failed." }),
	MyVoca("assort", VERB, { "classify", "separate", "divide", "group", "categorize", "class", "arrange", "methodize", "sort" }, { "It assort hundreds or thousands of products in a variety of ways, making it easier for consumers to see what they want." }),
	MyVoca("subjective", ADJ, { "personal", "individual", "particular", "idiosyncratic", "independent" }, { "Subjective judgments can sometimes lead to prejudice or misunderstanding, but subjective views are always necessary." }),
	MyVoca("presume", VERB, { "believe", "assume", "guess", "deduce", "imagine", "suppose" }, { "It is too hasty to presume that he is such a man by only one act and also it is a misunderstanding." }),
	MyVoca("relinquish", VERB, { "surrender", "abandon", "renounce", "resign" }, { "Because his faults were discovered, he had to relinquish everything he had, including wealth, honor, and power." }),
	MyVoca("intervention", NOUN, { "interference", "involvement", "intrusion", "intercession", "interposition", "interpolation", "mediation", "intermediation" }, { "President Bush has said he is open to all possible options for dealing with Iran, including military intervention." }),
	MyVoca("scrutiny", NOUN, { "inspection", "study", "examination", "analysis", "inquiry" }, { "The quality of Chinese goods has come under international scrutiny following scandals involving toothpaste, pet food and tires." }),
	MyVoca("apprehensive", ADJ, { "anxious", "concerned", "uneasy", "worried", "nervous", "fearful", "hesitant", "frightened" }, { "She was very nervous about the fact that her fault had twisted things up, and her friend soothed her well." }),

	MyVoca{ "-1", NOUN, { "" }, { "" } }, // end sentinel
};

#endif